---
# defaults file for roles/prometheus

prometheus_dir_configuration: "/etc/prometheus"
prometheus_node_exporter: true
prometheus_node_exporter_group: "all"
prometheus_var_config:
  global:
    scrape_interval: "30s"
    evaluation_interval: 5s
  scrape_configs:
    - job_name: prometheus
      scrape_interval: 5m
      static_configs:
        - targets: ['{{ inventory_hostname }}:9090']
