- name: install prometheus
  hosts: monitor
  become: yes
  roles:
  - prometheus

- name: install node-exporter
  hosts: all
  become: yes
  roles:
  - node-exporter

- name: Install Grafana
  hosts: monitor
  become: yes
  roles:
  - grafana