name: Upload Ansible configuration 

on: 
  workflow_dispatch:
    branches:
      - "*"
  push: 
    branches:
      - "create_pipeline_ansible_run_tests"
      - "check_passing_to_command_line"

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST_ADDRESS: ${{ vars.HOST_ADDRESS }}

jobs:
  deployconfiguration:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out 
        uses: actions/checkout@v3

      - name: Setting up SSH key
        working-directory: ./ansible_dir
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Run Ansible Playbook
        working-directory: ./ansible_dir
        run: |
          ls -lart | grep private_key
          cat private_key
          echo "Host address: $HOST_ADDRESS"
          sudo apt update
          sudo apt install -y ansible
          ansible-playbook -i inventory.yml playbook.yml --private-key=private_key.pem -e "target=4.245.250.242" -e "user=azureuser" -v


#           ansible-playbook -i inventory.yml playbook.yml --private-key="${{ secrets.SSH_PRIVATE_KEY }}" --user=${{ secrets.REMOTE_USER }} -e "{target: 4.245.250.242 }"
