name: Upload Ansible configuration 

on: 
  workflow_dispatch:
    branches:
      - "*"
  push: 
    branches:
      - "create_pipeline_ansible_run_tests"
      - "check_passing_to_command_line"
      - "try_without_unofficial_actions"

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST_ADDRESS: ${{ vars.HOST_ADDRESS }}

jobs:
  deployconfiguration:
      runs-on: ubuntu-latest
      steps: 
        - name: Check Out 
          uses: actions/checkout@v3

        - name: Setup SSH 
          shell: bash
          run: |
            eval `ssh-agent -s`
            mkdir -p /home/runner/.ssh/
            touch /home/runner/.ssh/id_rsa
            echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
            chmod 700 /home/runner/.ssh/id_rsa
            ssh-keyscan -t rsa ${{vars.HOST_ADDRESS}} >> /home/runner/.ssh/known_hosts
        - name: Run ansible script
          working-directory: ./ansible_dir
          shell: bash 
          run: |
            sudo apt update
            sudo apt install -y ansible
            service ssh status
            ansible-playbook -i inventory.yml playbook.yml --private-key=/home/runner/.ssh/id_rsa -e "target=4.245.250.242" -e "user=azureuser" -v
