name: Upload Ansible configuration 

on: 
  workflow_dispatch: 
  push: 
    branches:
      - "try_without_unofficial_actions"

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST_ADDRESS: ${{ vars.HOST_ADDRESS }}
  HOST_USER: ${{ vars.HOST_USER }}

jobs:
  deployconfiguration:
      runs-on: ubuntu-22.04
      steps: 
        - name: Check Out 
          uses: actions/checkout@v3

        - name: Install Ansible
          run: |
            sudo apt install -y ansible

        - name: Setup SSH 
          shell: bash
          run: |
            eval `ssh-agent -s`
            mkdir -p /home/runner/.ssh/
            touch /home/runner/.ssh/id_rsa
            echo -e "$SSH_PRIVATE_KEY" > /home/runner/.ssh/id_rsa
            chmod 700 /home/runner/.ssh/id_rsa
            ssh-keyscan -t rsa $HOST_ADDRESS >> /home/runner/.ssh/known_hosts

        - name: Run Ansible script
          working-directory: ./ansible_dir
          shell: bash 
          run: |
            service ssh status
            ansible-playbook -i inventory.yml playbook.yml --private-key=/home/runner/.ssh/id_rsa -e "target=$HOST_ADDRESS" -e "user=$HOST_USER" -v
