name: Upload Ansible configuration 

on: workflow_dispatch

jobs:
  deployconfiguration:
    runs-on: ubuntu-latest

    steps:
      - name: check out 
        uses: actions/checkout@v2
      - name: Setting up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Run Ansible Playbook
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-playbook -i inventory.yml playbook.yml \
          --private-key=private_key.pem \
          --user=${{ secrets.REMOTE_USER }} \
          -e "{target: env.HOST_ADDRESS}"
