name: Upload Ansible configuration 

on: 
  workflow_dispatch:
    branches:
      - "*"

jobs:
  deployconfiguration:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out 
        uses: actions/checkout@v3
      - name: Setting up SSH key
        working-directory: ./ansible_dir
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Run Ansible Playbook
        working-directory: ./ansible_dir
        run: |
          pwd
          ls -lart
          sudo apt update
          sudo apt install -y ansible
          ansible-playbook -i inventory.yml playbook.yml --private-key=private_key.pem --user=${{ secrets.REMOTE_USER }} -e "{target: ${{ env.HOST_ADDRESS}} }"
