name: Upload Ansible configuration 

on: 
  workflow_dispatch:
    branches:
      - "*"
  push: 
    branches:
      - "create_pipeline_ansible_run_tests"

jobs:
  deployconfiguration:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out 
        uses: actions/checkout@v3
      # - name: Setting up SSH key
      #   working-directory: ./ansible_dir
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
      #     chmod 600 private_key.pem
      #     ssh-add private_key.pem
      # - name: Install SSH key 
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     name: private_key # optional
      #     known_hosts: 4.245.250.242
      #     if_key_exists: fail 

      # - name: Run Ansible Playbook
      #   working-directory: ./ansible_dir
      #   run: |
      #     echo "Host address: ${{ env.HOST_ADDRESS }}"
      #     sudo apt update
      #     sudo apt install -y ansible
      #     ansible-playbook -i inventory.yml playbook.yml
      - name: Uruchom Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          playbook: playbook.yml
          inventory: inventory.yml
          options: |
            --verbose


#          ansible-playbook -i inventory.yml playbook.yml --private-key=private_key.pem --user=${{ secrets.REMOTE_USER }} -e "target=4.245.250.242" -e "user=azureuser" -v


#           ansible-playbook -i inventory.yml playbook.yml --private-key="${{ secrets.SSH_PRIVATE_KEY }}" --user=${{ secrets.REMOTE_USER }} -e "{target: 4.245.250.242 }"
